export const CREATE_ACCOUNT = 'CREATE_ACCOUNT';
export const IS_LOADING = 'IS_LOADING';
export const STORE_USER = 'STORE_USER';

export const NEW_ACCOUNT_REQUEST = 'NEW_ACCOUNT_REQUEST';
export const NEW_ACCOUNT_SUCCESS = 'NEW_ACCOUNT_SUCCESS';
export const NEW_ACCOUNT_FAILURE = 'NEW_ACCOUNT_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

export const COMPANY_REQUEST = 'COMPANY_REQUEST';
export const COMPANY_SUCCESS = 'COMPANY_SUCCESS';
export const COMPANY_FAILURE = 'COMPANY_FAILURE';

export const NEW_ORDER_REQUEST = 'NEW_ORDER_REQUEST';
export const NEW_ORDER_SUCCESS = 'NEW_ORDER_SUCCESS';
export const NEW_ORDER_FAILURE = 'NEW_ORDER_FAILURE';
export const REMOVE_ORDER = 'REMOVE_ORDER';

export const KEY_STORE_TOKEN = 'id_token';